In [1]:
from transformers import pipeline

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


#### Sentiment Analysis

In [2]:
classifier = pipeline("sentiment-analysis")
classifier("I've been waiting for a HuggingFace course my whole life.")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9598048329353333}]

In [3]:
classifier([
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"])

[{'label': 'POSITIVE', 'score': 0.9598048329353333},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]

#### Zero Shot Classification

In [4]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [5]:
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.8445988893508911, 0.11197423934936523, 0.04342683404684067]}

In [6]:
classifier(
    ["The monkey climbs the tree",
    "The dead monkey climbs the tree"],
    candidate_labels=['Impossible', 'Less Likely', 'Equally Likely', 'More Likely', 'Necessarily True'],
)

[{'sequence': 'The monkey climbs the tree',
  'labels': ['Equally Likely',
   'Less Likely',
   'More Likely',
   'Necessarily True',
   'Impossible'],
  'scores': [0.38330259919166565,
   0.24482421576976776,
   0.17974542081356049,
   0.16830293834209442,
   0.023824816569685936]},
 {'sequence': 'The dead monkey climbs the tree',
  'labels': ['Less Likely',
   'Equally Likely',
   'Necessarily True',
   'More Likely',
   'Impossible'],
  'scores': [0.34001874923706055,
   0.32802772521972656,
   0.154799222946167,
   0.14462944865226746,
   0.03252485394477844]}]

#### Text Generation

In [7]:
generator = pipeline("text-generation")
generator("In this course, we will teach you how to")

No model was supplied, defaulted to gpt2 and revision 6c0e608 (https://huggingface.co/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course, we will teach you how to:\n\nBuild a web application that supports JavaScript.\n\nCreate a custom web site\n\nA custom blog post in one of the web browsers.\n\nCreate an integrated database and record your'}]

using a different pretrained model for text generation

In [8]:
generator = pipeline("text-generation", model="distilgpt2")

In [9]:
generator(
    "In this course, we will teach you how to",
    max_length=30,
    num_return_sequences=2,
)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course, we will teach you how to use the tools available in the Java EE Studio to help you write more productive and effective Java code.'},
 {'generated_text': "In this course, we will teach you how to make your own music as a medium. You only have to get familiar with songs you'd like to"}]

#### Fill Mask Pipeline

In [10]:
unmasker = pipeline("fill-mask")

No model was supplied, defaulted to distilroberta-base and revision ec58a5b (https://huggingface.co/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [11]:
unmasker("This course will teach you all about <mask> models.", top_k=2)

[{'score': 0.19619806110858917,
  'token': 30412,
  'token_str': ' mathematical',
  'sequence': 'This course will teach you all about mathematical models.'},
 {'score': 0.04052723944187164,
  'token': 38163,
  'token_str': ' computational',
  'sequence': 'This course will teach you all about computational models.'}]

#### NER pipeline

In [12]:
ner = pipeline("ner", grouped_entities=True)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/usr/local/lib/python3.10/site-p

In [13]:
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

[{'entity_group': 'PER',
  'score': 0.9981694,
  'word': 'Sylvain',
  'start': 11,
  'end': 18},
 {'entity_group': 'ORG',
  'score': 0.9796019,
  'word': 'Hugging Face',
  'start': 33,
  'end': 45},
 {'entity_group': 'LOC',
  'score': 0.9932106,
  'word': 'Brooklyn',
  'start': 49,
  'end': 57}]

#### QA pipeline

In [14]:
question_answerer = pipeline("question-answering")
question_answerer(
    question="Where do I work?",
    context="My name is Sarthak and I work at University of Stuttgart in Stuttgart, Germany"
)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.7452282309532166,
 'start': 33,
 'end': 56,
 'answer': 'University of Stuttgart'}

#### Summarization Pipeline

In [ ]:
summarizer = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
summarizer("""Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]

In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[d] and has been criticised for its management of the crisis. A little over 1,000 people were killed, according to official records, three-quarters of whom were Muslim; independent sources estimated 2,000 deaths, mostly Muslim.[11] A Special Investigation Team appointed by the Supreme Court of India in 2012 found no evidence to initiate prosecution proceedings against him.[e] While his policies as chief minister, which were credited for encouraging economic growth, were praised, Modi's administration was criticised for failing to significantly improve health, poverty and education indices in the state.[f] In the 2014 Indian general election, Modi led the BJP to a parliamentary majority, the first for a party since 1984. His administration increased direct foreign investment, and it reduced spending on healthcare, education, and social-welfare programmes. Modi began a high-profile sanitation campaign, controversially initiated the 2016 demonetisation of high-denomination banknotes and introduced the Goods and Services Tax, and weakened or abolished environmental and labour laws.

Modi's administration launched the 2019 Balakot airstrike against an alleged terrorist training camp in Pakistan. The airstrike failed,[14][15] and the deaths of six Indian personnel to friendly fire was later revealed: but the action had nationalist appeal.[16] Modi's party comfortably won the 2019 general election which followed.[17] In its second term, his administration revoked the special status of Jammu and Kashmir, an Indian-administered portion of the disputed Kashmir region,[18][19] and introduced the Citizenship Amendment Act, prompting widespread protests, and spurring the 2020 Delhi riots in which Muslims were brutalised and killed by Hindu mobs,[20][21][22] sometimes with the complicity of police forces controlled by the Modi administration.[23][24] Three controversial farm laws led to sit-ins by farmers across the country, eventually causing their formal repeal. Modi oversaw India's response to the COVID-19 pandemic, during which 4.7 million Indians died, according to the World Health Organization's estimates.[25][26]

Under Modi's tenure, India has experienced democratic backsliding, or the weakening of democratic institutions, individual rights, and freedom of expression.[27][28][g] As prime minister, he has received consistently high approval ratings.[34][35][36] Modi has been described as engineering a political realignment towards right-wing politics. He remains a controversial figure domestically and internationally, over his Hindu nationalist beliefs and handling of the Gujarat riots, which have been cited as evidence of a majoritarian and exclusionary social agenda.[h]"""
          )

#### Translation Pipeline

In [ ]:
translator = pipeline("translation", model="SoyGema/english-hindi")

In [ ]:
translator("My name is Sarthak Singh and I am from New Delhi, India")

## Section 2

### Behind the pipeline

In [ ]:
from pprint import pprint

In [ ]:
from transformers import AutoTokenizer

In [ ]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!"
]

In [ ]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

In [ ]:
pprint(inputs)

In [ ]:
from transformers import AutoModel

In [ ]:
model = AutoModel.from_pretrained(checkpoint)

In [ ]:
outputs = model(**inputs)

In [ ]:
pprint(outputs.last_hidden_state.shape)

In [ ]:
# this will return error because AutoModel has no head, it can only return the hidden states
# pprint(outputs.logits)

Auto model for specific task

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [ ]:
outputs = model(**inputs)

In [ ]:
pprint(outputs.logits.shape)

In [ ]:
pprint(outputs.logits)

Now, let's do post processing

In [ ]:
import torch

In [ ]:
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

Let's test some of our own examples

In [ ]:
inputs = [
    "My day was not good, my dissapointment is immeasurable and my day is ruined.",
    "what are lovely day, let's hope no one fucks it up!"
]

In [ ]:
model_without_head = AutoModel.from_pretrained(checkpoint)

In [ ]:
processed_inputs = tokenizer(inputs, padding=True, truncation=True, return_tensors="pt")

In [ ]:
base_outputs = model_without_head(**processed_inputs)

In [ ]:
base_outputs.last_hidden_state.shape

In [ ]:
model_with_classification_head = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [ ]:
classification_outputs = model_with_classification_head(**processed_inputs)

In [ ]:
classification_outputs.logits, classification_outputs.logits.shape

In [ ]:
torch.nn.functional.softmax(classification_outputs.logits, dim=-1)

### Models

In [ ]:
checkpoint = "bert-base-cased"

In [ ]:
model = AutoModel.from_pretrained(checkpoint)

In [ ]:
type(model)

In [ ]:
from transformers import AutoConfig

In [ ]:
bert_base_config = AutoConfig.from_pretrained(checkpoint)
bert_base_config

In [ ]:
from transformers import BertConfig

In [ ]:
bert_base_config = BertConfig.from_pretrained(checkpoint)
bert_base_config

In [ ]:
from transformers import BertModel

In [ ]:
bert_base_config_modified = BertConfig.from_pretrained(checkpoint, num_hidden_layers=10)
bert_base_config_modified

In [ ]:
bert_model = BertModel(bert_base_config_modified)

In [ ]:
bert_model2 = AutoModel.from_config(bert_base_config_modified)

In [ ]:
type(bert_model)

In [ ]:
type(bert_model2)

we can also use default config

In [ ]:
config = BertConfig()
model = BertModel(config)

In [ ]:
config

In [ ]:
sequences = ["Hello.", "Hi!", "LOL."]

In [ ]:
checkpoint

In [ ]:
type(bert_model)

In [ ]:
bert_tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
encoded_sequences = bert_tokenizer(sequences)
encoded_sequences

In [ ]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [ ]:
model_inputs = torch.tensor(encoded_sequences)
model_inputs

In [ ]:
output = bert_model(model_inputs)
output

In [14]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [3]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [4]:
sentences = "I love huggingface."

In [6]:
tokens = tokenizer.tokenize(sentences, retu)
tokens

['i', 'love', 'hugging', '##face', '.']

In [9]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[1045, 2293, 17662, 12172, 1012]

In [10]:
import torch

In [12]:
input_ids = torch.tensor(ids)
input_ids

tensor([ 1045,  2293, 17662, 12172,  1012])

In [15]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [19]:
# model(input_ids) # This will give error because the tensor is 1D

In [21]:
input_ids = torch.tensor([ids])
input_ids

tensor([[ 1045,  2293, 17662, 12172,  1012]])

In [23]:
model(input_ids).logits

tensor([[-2.7084,  2.9112]], grad_fn=<AddmmBackward0>)

In [25]:
batched_ids = [ids, ids]
batched_ids = torch.tensor(batched_ids)
batched_ids

tensor([[ 1045,  2293, 17662, 12172,  1012],
        [ 1045,  2293, 17662, 12172,  1012]])

In [26]:
model(batched_ids).logits

tensor([[-2.7084,  2.9112],
        [-2.7084,  2.9112]], grad_fn=<AddmmBackward0>)

In [27]:
tokenizer.pad_token_id

0

In [34]:
ids1 = [[200, 200, 200]]
ids2 = [[200, 200]]
batches_id = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

In [35]:
print(model(torch.tensor(ids1)).logits)
print(model(torch.tensor(ids2)).logits)
print(model(torch.tensor(batches_id)).logits)

tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [36]:
# this difference in outputs is because of padding, we need attention  mask to solve this issue

In [37]:
attention_mask = [
    [1, 1, 1],
    [1, 1, 0]
]

In [39]:
print(model(torch.tensor(batches_id), attention_mask=torch.tensor(attention_mask)).logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


Now, it's working fine

In [125]:
sent1 = "I've been waiting for a HuggingFace course for my whole life!."
sent2 = "I hate this!"

In [126]:
sent1_ids = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sent1))
sent2_ids = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sent2))

In [127]:
print(sent1_ids)
print(sent2_ids)

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2005, 2026, 2878, 2166, 999, 1012]
[1045, 5223, 2023, 999]


In [128]:
sent2_len = len(sent2_ids)
new_sent2_ids = sent2_ids.copy()
for _ in range(len(sent1_ids) - len(sent2_ids)):
    new_sent2_ids.append(tokenizer.pad_token_id)

In [129]:
print(sent1_ids)
print(new_sent2_ids)

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2005, 2026, 2878, 2166, 999, 1012]
[1045, 5223, 2023, 999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [130]:
batches_ids = [sent1_ids, new_sent2_ids]
batches_ids

[[1045,
  1005,
  2310,
  2042,
  3403,
  2005,
  1037,
  17662,
  12172,
  2607,
  2005,
  2026,
  2878,
  2166,
  999,
  1012],
 [1045, 5223, 2023, 999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [131]:
attention_mask = list()
for batch_id in batches_ids:
    attention_mask.append([0 if item==tokenizer.pad_token_id else 1 for item in batch_id])

In [132]:
torch.tensor(batches_ids)

tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2005,  2026,  2878,  2166,   999,  1012],
        [ 1045,  5223,  2023,   999,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])

In [133]:
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [134]:
from pprint import pprint

In [135]:
print(torch.tensor([sent1_ids]))
print(torch.tensor([sent2_ids]))
print(torch.tensor(batches_ids))
print(torch.tensor(attention_mask))

tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2005,  2026,  2878,  2166,   999,  1012]])
tensor([[1045, 5223, 2023,  999]])
tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2005,  2026,  2878,  2166,   999,  1012],
        [ 1045,  5223,  2023,   999,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [137]:
print(model(torch.tensor([sent1_ids])).logits)
print(model(torch.tensor([sent2_ids])).logits)
print(model(torch.tensor(batches_ids), attention_mask=torch.tensor(attention_mask)).logits)

tensor([[-2.7206,  2.8660]], grad_fn=<AddmmBackward0>)
tensor([[ 3.6696, -3.0004]], grad_fn=<AddmmBackward0>)
tensor([[-2.7206,  2.8660],
        [ 3.6696, -3.0004]], grad_fn=<AddmmBackward0>)


In [138]:
batches_id

[1045, 5223, 2023, 999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [139]:
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

# Will truncate the sequences that are longer than the model max length
# (512 for BERT or DistilBERT)
model_inputs = tokenizer(sequences, truncation=True)

# Will truncate the sequences that are longer than the specified max length
model_inputs = tokenizer(sequences, max_length=8, truncation=True)

In [140]:
model_inputs

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 102], [101, 2061, 2031, 1045, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [150]:
tokenizer(sequences[0])['input_ids']

[101,
 1045,
 1005,
 2310,
 2042,
 3403,
 2005,
 1037,
 17662,
 12172,
 2607,
 2026,
 2878,
 2166,
 1012,
 102]

In [151]:
tokenizer.convert_tokens_to_ids(tokenizer.tokenize(sequences[0]))

[1045,
 1005,
 2310,
 2042,
 3403,
 2005,
 1037,
 17662,
 12172,
 2607,
 2026,
 2878,
 2166,
 1012]

101 and 102 are special tokens

In [152]:
tokenizer.decode(tokenizer(sequences[0])['input_ids'])

"[CLS] i've been waiting for a huggingface course my whole life. [SEP]"

In [153]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [154]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")
output = model(**tokens)

In [155]:
output.logits

tensor([[-1.5607,  1.6123],
        [-3.6183,  3.9137]], grad_fn=<AddmmBackward0>)

In [156]:
tokens

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  2061,  2031,  1045,   999,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}

** passes the dictionary as a keyword argument to the constructor of model